### ISSUE TITLE
ruamel deprecation error

### ISSUE THREAD

**Issue by joewa** [ThGaskin/NeuralABM#43]
Hello,

when following the recipe, I am getting a ruamel deprecation error when running:

`$ utopya run Kuramoto models/Kuramoto/Kuramoto_cfg.yml`

This is the Traceback:
```
HILIGHT  logging           Starting to work ...

    ╠                                                                      ╣   0.0% |    < 1s elapsed | ~      ∞ left
  uni0 out:  Traceback (most recent call last):
  uni0 out:    File "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329, in <module>
  uni0 out:      cfg = yaml.load(cfg_file, Loader=yaml.Loader)
  uni0 out:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  uni0 out:    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
  uni0 out:      error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  uni0 out:    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
  uni0 out:      raise AttributeError(s, name=None)
  uni0 out:  AttributeError:
  uni0 out:  "load()" has been removed, use
  uni0 out:
  uni0 out:    yaml = YAML(typ='rt')
  uni0 out:    yaml.load(...)
  uni0 out:
  uni0 out:  and register any classes that you use, or check the tag attribute on the loaded data,
  uni0 out:  instead of file "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329
  uni0 out:
  uni0 out:          cfg = yaml.load(cfg_file, Loader=yaml.Loader)
  uni0 out:
  uni0 out:
    ╠░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╣   0.0% |      1s elapsed | ~      ∞ left
CRITICAL workermanager     Task 'uni0' exited with non-zero exit status: 1.
This may originate from the following signals:  SIGHUP, SIG_IGN, SIG_UNBLOCK.
Googling these might help with identifying the error. Also, inspect the log and the log file for further error messages. To increase verbosity, run in debug mode, e.g. by passing the --debug flag to the CLI.
ERROR    workermanager     Last ≤24 lines of combined stdout and stderr:

  Traceback (most recent call last):
    File "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329, in <module>
      cfg = yaml.load(cfg_file, Loader=yaml.Loader)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
      error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
      raise AttributeError(s, name=None)
  AttributeError:
  "load()" has been removed, use

    yaml = YAML(typ='rt')
    yaml.load(...)

  and register any classes that you use, or check the tag attribute on the loaded data,
  instead of file "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329

          cfg = yaml.load(cfg_file, Loader=yaml.Loader)



CRITICAL workermanager     Did not finish working! See above for error log.
HILIGHT  logging           Terminating active tasks ...
    ╠▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╣ 100.0% | finished in 1s
CRITICAL workermanager     Exiting now ...
```

These are the ruamel versions in my environment:
```
$ conda list ruamel
# packages in environment at /home/joerg/miniforge3/envs/neuralabm:
#
# Name                    Version                   Build  Channel
ruamel-base               1.0.0                    pypi_0    pypi
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
```

I will have a quick look if the hint fixes the error...

**Comment by ThGaskin** [comment]
I believe ruamel.yaml>=0.18 is incompatible with utopya — try installing <0.18?

On 10. Dec 2023, at 22:42, Joerg Wangemann ***@***.***> wrote:

﻿

Hello,

when following the recipe, I am getting a ruamel deprecation error when running:

$ utopya run Kuramoto models/Kuramoto/Kuramoto_cfg.yml

This is the Traceback:

HILIGHT  logging           Starting to work ...

    ╠                                                                      ╣   0.0% |    < 1s elapsed | ~      ∞ left
  uni0 out:  Traceback (most recent call last):
  uni0 out:    File "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329, in <module>
  uni0 out:      cfg = yaml.load(cfg_file, Loader=yaml.Loader)
  uni0 out:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  uni0 out:    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
  uni0 out:      error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  uni0 out:    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
  uni0 out:      raise AttributeError(s, name=None)
  uni0 out:  AttributeError:
  uni0 out:  "load()" has been removed, use
  uni0 out:
  uni0 out:    yaml = YAML(typ='rt')
  uni0 out:    yaml.load(...)
  uni0 out:
  uni0 out:  and register any classes that you use, or check the tag attribute on the loaded data,
  uni0 out:  instead of file "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329
  uni0 out:
  uni0 out:          cfg = yaml.load(cfg_file, Loader=yaml.Loader)
  uni0 out:
  uni0 out:
    ╠░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╣   0.0% |      1s elapsed | ~      ∞ left
CRITICAL workermanager     Task 'uni0' exited with non-zero exit status: 1.
This may originate from the following signals:  SIGHUP, SIG_IGN, SIG_UNBLOCK.
Googling these might help with identifying the error. Also, inspect the log and the log file for further error messages. To increase verbosity, run in debug mode, e.g. by passing the --debug flag to the CLI.
ERROR    workermanager     Last ≤24 lines of combined stdout and stderr:

  Traceback (most recent call last):
    File "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329, in <module>
      cfg = yaml.load(cfg_file, Loader=yaml.Loader)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
      error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
    File "/home/joerg/miniforge3/envs/neuralabm/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
      raise AttributeError(s, name=None)
  AttributeError:
  "load()" has been removed, use

    yaml = YAML(typ='rt')
    yaml.load(...)

  and register any classes that you use, or check the tag attribute on the loaded data,
  instead of file "/home/joerg/repos/NeuralABM/models/Kuramoto/run.py", line 329

          cfg = yaml.load(cfg_file, Loader=yaml.Loader)



CRITICAL workermanager     Did not finish working! See above for error log.
HILIGHT  logging           Terminating active tasks ...
    ╠▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╣ 100.0% | finished in 1s
CRITICAL workermanager     Exiting now ...


These are the ruamel versions in my environment:

$ conda list ruamel
# packages in environment at /home/joerg/miniforge3/envs/neuralabm:
#
# Name                    Version                   Build  Channel
ruamel-base               1.0.0                    pypi_0    pypi
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi


I will have a quick look if the hint fixes the error...

**Comment by ThGaskin** [comment]
Hi, 

just to let you I've reworked the README and added a tutorial -- perhaps this will make it easier for you to use and play around with the code :)

Best, 

Thomas
